Create UserDefinedExpression feature
domaframework/doma pull request #1102
Opened 2024-04-29 16:03 UTC by momosetkn

```java

2024-04-29 16:20 UTC, momosetkn commented on doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/UserDefinedExpression.java
> +  }
For doma-kotlin, it will be primitive type

2024-05-02 01:25 UTC, nakamura-to commented
Thank you for the pull request.
I plan to review it within a few days.

2024-05-06 07:54 UTC, nakamura-to requested changes

2024-05-06 10:36 UTC, momosetkn commented on doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/UserDefinedExpression.java
> +      Class<PROPERTY> klass, EntityPropertyType<?, ?> type, Consumer<Declaration> block) {
Sorry, How do I obtain a class object using type? or
obtain from PropertyMetamodel?

2024-05-06 11:08 UTC, nakamura-to commented on doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/UserDefinedExpression.java
> +      Class<PROPERTY> klass, EntityPropertyType<?, ?> type, Consumer<Declaration> block) {
I was mistaken. I meant to say that by accepting a parameter of type `PropertyMetamodel`, both `Class` and `EntityPropertyType` can be resolved.

2024-05-06 11:30 UTC, momosetkn commented on doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/UserDefinedExpression.java
> +  public static class Declaration implements SqlContext {
Is it okay to omit appendParameter?
I didn't have a use-case for it, and I can almost achieve the same functionality with Expressions.literal, plus I wasn't meeting the test coverage.

2024-05-06 11:37 UTC, nakamura-to commented on doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/UserDefinedExpression.java
> +  public static class Declaration implements SqlContext {
> Is it okay to omit appendParameter?

Yes, it's okay.
If someone makes a request in the future, we will consider it.

2024-05-19 14:27 UTC, momosetkn commented
@nakamura-to 
I'm sorry I'm late.
Refactoring is complete.
I implemented the equals and hashCode method in UserDefinedExpression, similar to the others.

2024-05-26 08:36 UTC, merged

2024-05-26 08:40 UTC, nakamura-to commented
Thank you!